// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240320021619_FillTable")]
    partial class FillTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Data.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("afb101e0-ba1b-45fe-9a56-50fa700aeeaa"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 1, 20, 2, 16, 19, 215, DateTimeKind.Utc).AddTicks(6827),
                            Description = "Activity 2 months ago",
                            Name = "Past Activity 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            Id = new Guid("cd378633-bb0c-4ed2-ae22-036e882647bf"),
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2024, 2, 20, 2, 16, 19, 215, DateTimeKind.Utc).AddTicks(6844),
                            Description = "Activity 1 month ago",
                            Name = "Past Activity 2",
                            Venue = "Louvre"
                        },
                        new
                        {
                            Id = new Guid("8d7afb49-1c23-43e0-95b1-a50fa8016ef3"),
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2024, 4, 20, 2, 16, 19, 215, DateTimeKind.Utc).AddTicks(6846),
                            Description = "Activity 1 month in future",
                            Name = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            Id = new Guid("2290bac4-4ac7-4d57-88e0-92489c0af1ff"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2024, 5, 20, 2, 16, 19, 215, DateTimeKind.Utc).AddTicks(6849),
                            Description = "Activity 2 months in future",
                            Name = "Future Activity 2",
                            Venue = "O2 Arena"
                        },
                        new
                        {
                            Id = new Guid("a6ef5866-71a6-4918-b434-7b8bf232aa6a"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 6, 20, 2, 16, 19, 215, DateTimeKind.Utc).AddTicks(6853),
                            Description = "Activity 3 months in future",
                            Name = "Future Activity 3",
                            Venue = "Another pub"
                        },
                        new
                        {
                            Id = new Guid("1cd29ac6-b45b-4c84-b236-407a5a8e1778"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 7, 20, 2, 16, 19, 215, DateTimeKind.Utc).AddTicks(6855),
                            Description = "Activity 4 months in future",
                            Name = "Future Activity 4",
                            Venue = "Yet another pub"
                        },
                        new
                        {
                            Id = new Guid("1036304c-c007-4618-a85d-394a66d71ae8"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2024, 8, 20, 2, 16, 19, 215, DateTimeKind.Utc).AddTicks(6857),
                            Description = "Activity 5 months in future",
                            Name = "Future Activity 5",
                            Venue = "Just another pub"
                        },
                        new
                        {
                            Id = new Guid("ec3dd68c-7b53-49fe-9b1e-8235bc0ca635"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2024, 9, 20, 2, 16, 19, 215, DateTimeKind.Utc).AddTicks(6864),
                            Description = "Activity 6 months in future",
                            Name = "Future Activity 6",
                            Venue = "Roundhouse Camden"
                        },
                        new
                        {
                            Id = new Guid("3622e507-db14-4652-ae06-f33c7cb65c2c"),
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2024, 10, 20, 2, 16, 19, 215, DateTimeKind.Utc).AddTicks(6867),
                            Description = "Activity 2 months ago",
                            Name = "Future Activity 7",
                            Venue = "Somewhere on the Thames"
                        },
                        new
                        {
                            Id = new Guid("f28cda24-c5d6-47e3-828c-75700d5838fb"),
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2024, 11, 20, 2, 16, 19, 215, DateTimeKind.Utc).AddTicks(6869),
                            Description = "Activity 8 months in future",
                            Name = "Future Activity 8",
                            Venue = "Cinema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
